export const ADD_NEW_ADMIN_REQUEST="ADD_NEW_ADMIN_REQUEST"
export const ADD_NEW_ADMIN_SUCCESS="ADD_NEW_ADMIN_SUCCESS"
export const ADD_NEW_ADMIN_FAIL="ADD_NEW_ADMIN_FAIL"

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"
export const LOGOUT="LOGOUT"

export const GET_ADMIN_DETAILS_REQUEST="GET_ADMIN_DETAILS_REQUEST"
export const GET_ADMIN_DETAILS_SUCCESS="GET_ADMIN_DETAILS_SUCCESS"
export const GET_ADMIN_DETAILS_FAIL="GET_ADMIN_DETAILS_FAIL"