export const GET_CAREGIVER_REQUEST="GET_CAREGIVER_REQUEST"
export const GET_CAREGIVER_REQUEST_SUCCESS="GET_CAREGIVER_REQUEST_SUCCESS"
export const GET_CAREGIVER_REQUEST_FAIL="GET_CAREGIVER_REQUEST_FAIL"

export const GET_ONECAREGIVER_REQUEST="GET_CAREGIVER_REQUEST"
export const GET_ONECAREGIVER_REQUEST_SUCCESS="GET_CAREGIVER_REQUEST_SUCCESS"
export const GET_ONECAREGIVER_REQUEST_FAIL="GET_CAREGIVER_REQUEST_FAIL"

export const ADD_NEW_CAREGIVER_REQUEST="ADD_NEW_CAREGIVER_REQUEST"
export const ADD_NEW_CAREGIVER_SUCCESS="ADD_NEW_CAREGIVER_SUCCESS"
export const ADD_NEW_CAREGIVER_FAIL="ADD_NEW_CAREGIVER_FAIL"

export const CARE_LOGIN_REQUEST="CARE_LOGIN_REQUEST"
export const CARE_LOGIN_SUCCESS="CARE_LOGIN_SUCCESS"
export const CARE_LOGIN_FAIL="CARE_LOGIN_FAIL"
export const LOGOUT="LOGOUT"

export const DELETE_CAREGIVER_REQUEST="DELETE_CAREGIVER_REQUEST"
export const DELETE_CAREGIVER_SUCCESS="DELETE_CAREGIVER_SUCCESS"
export const DELETE_CAREGIVER_FAIL="DELETE_CAREGIVER_FAIL"

export const UPDTAE_CAREGIVER_REQUEST="UPDTAE_CAREGIVER_REQUEST"
export const UPDTAE_CAREGIVER_SUCCESS="UPDTAE_CAREGIVER_SUCCESS"
export const UPDTAE_CAREGIVER_FAIL="UPDTAE_CAREGIVER_FAIL"

// export const SEARCH_CAREGIVERBYADRESSE ="SEARCH_CAREGIVERBYADRESSE"
// export const SEARCH_CAREGIVERBYADRESSE_SUCCESS="SEARCH_CAREGIVERBYADRESSE_SUCCESS"
// export const SEARCH_CAREGIVERBYADRESSE_FAIL="SEARCH_CAREGIVERBYADRESSE_FAIL"