export const ADD_REVIEW_REQUEST= 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS= 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL= 'ADD_REVIEW_FAIL';



export const DELETE_REVIEW_REQUEST='DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL='DELETE_REVIEW_FAIL';
// export const UPDATE_REVIEWBYID= 'UPDATE_REVIEW';


export const GET_ALL_REVIEWBYID_REQUEST= 'GET_ALL_REVIEWBYIDREQUEST';
export const GET_ALL_REVIEWBYID_SUCCESS='GET_ALL_REVIEWBYID_SUCCESS'
export const  GET_ALL_REVIEWBYID_REQUEST_FAIL=" GET_ALL_REVIEWBYID_REQUEST_FAIL"
